name: Deploy Development Build

on:
  push:
    # On push to "development" branch for relevant files
    branches:
      - development
    paths:
      - .github/**
      - files/**
      - Dockerfile
  schedule:
    # Run 05:00 UTC every TUE, FRI
    - cron: "0 5 * * 2,5"
  # On-demand push-button build, why not...
  workflow_dispatch:

jobs:
  get_latest_version:
    uses: ./.github/workflows/get_nexus_version_latest.yml

  build_deploy_to_registry:
    runs-on: ubuntu-latest
    needs: get_latest_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Enable docker cache to speed-up builds
      - name: Setup Docker build cache
        uses: actions/cache@v3
        with:
          path: /tmp/buildx-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-

      # Enable multi-architecture support on build node
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        if: steps.set_nexus_version.outputs.new_version
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.set_nexus_version.outputs.new_version
        uses: docker/build-push-action@v5
        with:
            context: .
            push: false
            build-args: |
              NEXUS_VERSION=${{ steps.set_nexus_version.outputs.new_version }}
            tags: |
              ghcr.io/${{ github.repository }}:development
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            cache-from: type=gha
            cache-to: type=gha,mode=max
